# Generated by Django 2.1.5 on 2019-02-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_profile', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='profiles',
            field=models.ManyToManyField(to='default_profile.DefaultProfile'),
        ),
    ]
