# Generated by Django 2.1.5 on 2019-02-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='profiles',
        ),
    ]
