# Generated by Django 2.1.5 on 2019-02-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_service_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='primary_poc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='secondary_poc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
