# Generated by Django 2.1.5 on 2019-06-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
