# Generated by Django 2.1.5 on 2019-02-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('deployment', models.CharField(blank=True, max_length=50, null=True)),
                ('deployed', models.DateField(auto_now_add=True)),
                ('standard_build', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('developer', models.CharField(default='COB', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
