# Generated by Django 2.1.5 on 2019-02-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_service_profiles'),
        ('default_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultprofile',
            name='services',
            field=models.ManyToManyField(to='service.Service'),
        ),
    ]
