# Generated by Django 2.1.5 on 2019-03-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountimage',
            old_name='image',
            new_name='full_image',
        ),
        migrations.AddField(
            model_name='accountimage',
            name='cropped_image',
            field=models.ImageField(default='old_image', upload_to='%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
