# Generated by Django 2.1.5 on 2019-03-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_image', '0003_remove_accountimage_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountimage',
            name='cropped_image',
            field=models.FileField(upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='accountimage',
            name='full_image',
            field=models.FileField(upload_to='%Y/%m/%d'),
        ),
    ]
