# Generated by Django 2.1.5 on 2019-02-01 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='department',
            field=models.CharField(default='department', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='division',
            field=models.CharField(default='division', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='employee_phone',
            field=models.CharField(default='employee_phone', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='facility',
            field=models.CharField(default='facility', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='first_name',
            field=models.CharField(default='first_name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='group',
            field=models.CharField(default='group', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='job',
            field=models.CharField(default='job', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='last_name',
            field=models.CharField(default='last_name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='middle_name',
            field=models.CharField(default='middle_name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='suffix',
            field=models.CharField(default='suffix', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='supervisor',
            field=models.CharField(default='supervisor', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='supervisor_phone',
            field=models.CharField(default='supervisor_phone', max_length=50),
            preserve_default=False,
        ),
    ]
