# Generated by Django 2.1.5 on 2019-02-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20190201_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='status',
            new_name='employee_status',
        ),
        migrations.AddField(
            model_name='request',
            name='request_status',
            field=models.CharField(default='request_status', max_length=50),
            preserve_default=False,
        ),
    ]
