# Generated by Django 2.1.5 on 2019-06-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(max_length=150),
        ),
    ]
