# Generated by Django 2.1.5 on 2019-02-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequest',
            name='division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='facility',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
