# Generated by Django 2.1.5 on 2019-02-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_request', '0002_auto_20190214_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
