# Generated by Django 2.1.5 on 2019-02-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_request', '0004_accountrequest_requested_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrequest',
            name='requested_services',
        ),
    ]
