# Generated by Django 2.1.5 on 2019-02-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_request', '0007_accountrequest_requested_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
