# Generated by Django 2.1.5 on 2019-06-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_request', '0012_auto_20190312_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequest',
            name='supervisor_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
