# Generated by Django 3.0.3 on 2020-02-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_request', '0013_auto_20190603_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequest',
            name='supervisor_phone',
            field=models.CharField(default=8675309, max_length=12),
            preserve_default=False,
        ),
    ]
