# Generated by Django 2.1.5 on 2019-02-12 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(max_length=10)),
                ('employee_phone', models.CharField(max_length=10)),
                ('supervisor', models.CharField(max_length=50)),
                ('supervisor_phone', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('facility', models.CharField(max_length=50)),
                ('clock_entry_only', models.BooleanField(default=False)),
                ('job', models.CharField(max_length=50)),
                ('employee_status', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('dynamic_options', models.TextField(blank=True, null=True)),
                ('request_status', models.CharField(max_length=50)),
                ('requested', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
