# Generated by Django 2.1.5 on 2019-02-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_request', '0006_auto_20190222_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='requested_services',
            field=models.TextField(blank=True, null=True),
        ),
    ]
