# Generated by Django 2.1.5 on 2019-03-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_request', '0010_auto_20190307_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountrequest',
            old_name='full_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='accountrequest',
            name='cropped_image',
        ),
    ]
