# Generated by Django 2.1.5 on 2019-03-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_request', '0008_accountrequest_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
