# Generated by Django 2.1.5 on 2019-03-07 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_request', '0009_accountrequest_end_date'),
    ]

    operations = [
    ]
