# Generated by Django 2.1.5 on 2019-03-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_request', '0011_auto_20190307_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='cropped_image',
            field=models.FileField(null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='full_image',
            field=models.FileField(null=True, upload_to='%Y/%m/%d'),
        ),
    ]
